project:
  type: book

book:
  title: "Signal Correlation"
  author: "Asher"
  date: "14/5/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - seq.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
  pdf:
    documentclass: scrreprt



