# Fundamentals


::: {#def-group}
## Group
A set $G$, one operators $\cdot$ form $(G,\cdot)$ such that
- *Associativity*: $\forall a,b,c \in A$
    $$(a \cdot b) \cdot c = a \cdot (b \cdot c)$$
- *Identity element*: $\forall a \in A, \exists ! e \in A$
    $$e \cdot a = a \cdot e$$
- *Inverse element*: $\forall a \in A, \exists ! b \in A$
    $$a \cdot b = b \cdot a = e$$
::: {.callout-note}
$\exists !$ is the [uniqueness existential quantification](#https://en.wikipedia.org/wiki/Uniqueness_quantification).
:::
:::


::: {#def-group-order}
## Group order
The **order**of a finite group is the number of its elements.

The *order* of group G is denoted by $ord(G)$ or $|G|$.
:::


::: {#def-group-element-order}
## Element order (Period, or Period length)
The **order** or **period length** or **period** of an element of a finite group is the *order* of the subgroup generated by the element.

The generated group (strictly speaking, subgroup) is denoted by $\langle a \rangle$.

If the generated group is $(G,\cdot)$ and $a \in G$
$$\langle a \rangle = \{a^k:k \in \mathbb{Z}\}$$

The *order* of element $a$ is denoted by $ord(a)$ or $|a|$ for symplicity. It is actually
$$ord(a) = ord(\langle a \rangle)$$


$\forall n \in \mathbb{Z}, a \in G$ and the identity $e$,
$$a^n = e \iff ord(a) \mid n$$
:::


::: {#def-abelian-group}
## Abelian group (Commutative group)
A set $A$, one operators $\cdot$ form $(A,\cdot)$ such that

- *Associativity*: $\forall a,b,c \in A$
    $$(a \cdot b) \cdot c = a \cdot (b \cdot c)$$
- *Identity element*: $\forall a \in A, \exists e \in A$
    $$e \cdot a = a \cdot e$$
- *Inverse element*: $\forall a \in A, \exists b \in A$
    $$a \cdot b = b \cdot a = e$$
- *Commutativity*: $\forall a,b \in A$
    $$a \cdot b = b \cdot a$$
:::


::: {#def-ring}
## Ring
Rings are algebraic structures that generalize fields such that

- Multiplication needs *not* to be *commutative*
- *Multiplicative inverses* need *not* exist.

Formally, a set $R$, two operators addtion $+$ and multiplication $\cdot$ forms $(R,+,\cdot)$ such that

- R is an *Abelian group* (@def-abelian-group) w.r.t $+$.
- *Associativity*: $\forall a,b,c \in R$
    $$(a \cdot b) \cdot c = a \cdot (b \cdot c)$$
- *Distributivity*: $\forall $a,b,c \in R$
    $$a \cdot (b + c) = (a \cdot b) + (a \cdot c), and (a + b) \cdot c = (a \cdot c) + (b \cdot c)$$
:::{.callout-note}
Note that the operator $\cdot$ in @def-abelian-group and @def-ring are not relevant.
:::
:::


::: {#def-field}
## Field
A field consists of

- A *Ring* (@def-ring) $(F,+,\cdot)$
- $F^* = \{a \in F \mid a \neq 0\}$ forms an Abelian group w.r.t multiplication $\cdot$ : $(F^*,\cdot)$
:::

More specificly, $\forall a,b,c \in F$, the following [**field axioms**]{#def-field-axim} holds

- *Associativity* of *addition* and *multiplication*: $a + (b + c) = (a + b) + c$, and $a ⋅ (b ⋅ c) = (a ⋅ b) ⋅ c$.
- *Commutativity* of *addition* and *multiplication*: $a + b = b + a$, and $a ⋅ b = b ⋅ a$.
- *Additive* and *multiplicative* *identity*: there exist two different elements $0$ and $1$ in $F$ such that $a + 0 = a$ and $a ⋅ 1 = a$.
- *Additive* *inverses*: for every $a$ in $F$, there exists an element in F, denoted $−a$, called the additive inverse of $a$, such that $a + (−a) = 0$.
- *Multiplicative* **inverses**: for every $a ≠ 0$ in $F$, there exists an element in $F$, denoted by $a^{−1}$ or $\frac{1}{a}$, called the multiplicative inverse of a, such that $a ⋅ a^{−1} = 1$.
- *Distributivity* of multiplication over addition: a ⋅ (b + c) = (a ⋅ b) + (a ⋅ c).


::: {#def-finite-field}
## Finite Field (Galois Field)
A finite set that the operators $\cdot,+,-,/$ satisfy the [field axims](#def-field-axim).
:::

The [**order** or **size**]{#def-field-order} of a finite field is the number of its elements.


::: {#thm-finite-field-order}
A finite field of order $q$ exists $\iff q=p^n$, where $p$ is a prime number, $n \in \mathbb{Z}_{\geq 1}$
:::

::: {#thm-fermat-little}
## Fermat's Little Theorem
If $p$ is a prime number, $\forall x \in \mathbb{Z}
$$x^p \equiv x \pmod p$$
or equivalently
$$x^{p-1} \equiv 1 \pmod p$$
:::
::: {.proof}
Assuming $p$ is a prime number, the set $G = \{1,2,\dots,p-1\}$ forms a finite group (@def-group) w.r.t $\cdot \pmod p$

See [proofs using group theory](https://en.wikipedia.org/wiki/Proofs_of_Fermat%27s_little_theorem#Proofs_using_group_theory)
:::